baseURL = 'https://deryck2000.jp.eu.org/'
languageCode = 'ja-ja'
defaultContentLanguage = 'ja'
title = 'デデオチャンのサイト'
theme = 'nostyleplease'
publishDir = "docs"

[params]
  author = "deryck2000"
  description = """デデオチャンです！
  あんかけラーメンが好き"""
  github = "Deryck2000"
  url = "https://deryck2000.jp.eu.org/"
  rss = true
  lastmod = true
  location = "Japan"
    favicon = "/favicon.ico"
  avatar = "/dedeo_icon.gif"
  headerIcon = "/favicon.ico"
[taxonomies]
  tag = "tags"
  category = "categories"

  [[params.links]]
    title = "Link"
    href = "https://deryck2000.jp.eu.org/"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

  [markup.goldmark.renderer]
  unsafe = true